matrix:
- name: markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.text
  sources:
  - 'content/**/*.md'
  default_encoding: utf-8
