matrix:
- name: markdown
  aspell:
    lang: en
    camel-case: true
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - 'content/**/*.md'
  default_encoding: utf-8
  re_exclude:
  - '\[.*?\]\([^\s)]+\)' # Matches [link text](url)
  - 'https?://[^\s)]+'          # Matches standalone URLs
