name: Build Retype website for GitHub Pages

on:
  # Allows manual triggering of the workflow from the Actions tab.
  workflow_dispatch:

  # Triggers the workflow on push events to the 'main' branch.
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    # Runs the job on an Ubuntu virtual machine.
    runs-on: ubuntu-latest

    # Grants the job write permissions to the repository's contents.
    permissions:
      contents: write

    steps:
      # Checks out the repository's code to the virtual machine.
      - uses: actions/checkout@v4

      # Sets up the .NET SDK, version 7.0.x, required for Retype's build process.
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      # Builds the Retype website using the official Retype GitHub Action.
      # The Retype license is securely passed as a secret.
      - uses: retypeapp/action-build@latest
        with:
          license: ${{ secrets.RETYPE_SECRET }}

      # Publishes the built website to GitHub Pages using the Retype GitHub Action.
      # The 'update-branch' option updates the 'retype' branch with the built website.
      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
