name: Run spell check

on:
    push:
        branches:
            - main
        paths:
            - "**.md"
            - ".github/.wordlist.txt"
    pull_request:
        paths:
            - "**.md"
            - ".github/.wordlist.txt"
    workflow_dispatch:

jobs:
    check-spellcheck:
        name: Check Spelling - pyspelling
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: rojopolis/spellcheck-github-actions@0.48.0
